// Code generated by qtc from "ukraine-universities-rating-by-faang.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package v1

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamUkraineUniversitiesRatingByFAANG(qw422016 *qt422016.Writer, universities []University) {
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">
<head>
    <title>Ukraine universities rating by FAANG</title>
    <meta name="description" content="Ukraine universities rating by FAANG">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="author" type="text/plain" href="https://gocompanies.readytotouch.com/humans.txt"/>

	`)
	streamfavicon(qw422016)
	qw422016.N().S(`

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-VCD3QKRT9Z"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-VCD3QKRT9Z');
    </script>
    <style>
        td {
            padding-top:5px;
            padding-bottom:5px;
            padding-right:5px;
        }

        td:first-child {
            padding-left:5px;
            padding-right:0;
        }
    </style>
</head>
<body>
    <h1>Ukraine universities rating by FAANG</h1>
    <table border="1">
        <tr>
            <th>Name</th>
        </tr>
        `)
	for i, university := range universities {
		qw422016.N().S(`
            <tr>
                <td>
                    `)
		qw422016.N().D(i)
		qw422016.N().S(` | <a href="https://www.linkedin.com/school/`)
		qw422016.E().S(university.LinkedInProfile.Alias)
		qw422016.N().S(`/">`)
		qw422016.E().S(university.LinkedInProfile.Name)
		qw422016.N().S(`</a>
                </td>
            </tr>
        `)
	}
	qw422016.N().S(`
    </table>

    <footer>
        <p>© 2024 <a href="https://readytotouch.com/">ReadyToTouch</a></p>
    </footer>
</body>
</html>
`)
}

func WriteUkraineUniversitiesRatingByFAANG(qq422016 qtio422016.Writer, universities []University) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamUkraineUniversitiesRatingByFAANG(qw422016, universities)
	qt422016.ReleaseWriter(qw422016)
}

func UkraineUniversitiesRatingByFAANG(universities []University) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteUkraineUniversitiesRatingByFAANG(qb422016, universities)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
